ControleEstoque/Controllers/Cadastro/GrupoProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ControleEstoque.Models;
using Newtonsoft.Json.Linq;

namespace ControleEstoque.Controllers
{
    public class GrupoProdutoController : Controller
    {


        private const int _quantMaxLinhasPorPagina = 5;

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]//Valida o token gerado pelo usuario, utilizamos isso para evitar ataques CRSF
        public ActionResult RecuperarGrupoProduto(int id)
        {
            return Json(GrupoProdutoModel.findGrupoProduto(id));
        }

        [HttpPost] //Tipo de requisição
        [Authorize]
        [ValidateAntiForgeryToken]//Valida o token gerado pelo usuario, utilizamos isso para evitar ataques CRSF
        public ActionResult ExcluirGrupoProduto(int id)
        {
            return Json(GrupoProdutoModel.deleteGrupoProduto(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken] //Valida o token gerado pelo usuario, utilizamos isso para evitar ataques CRSF
        public ActionResult SalvarGrupoProduto(GrupoProdutoModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = "";
            Console.WriteLine("Passou aqui");

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();//Retorna os objetos que tiveram erros selecione muitos valores e transforma em lista
            }
            else
            {
                try
                {
                    var id = model.salvarGrupoProduto();

                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }

            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }

        [Authorize]
        public ActionResult Index()
        {
            var lista = GrupoProdutoModel.RecuperarLista(1, _quantMaxLinhasPorPagina);
            ViewBag.ListaTamanhoPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QtdMaximaLinhasPagina = 5; //Quando estamos fazendo paginação é necessario informar a quantidade de linhas da table será exibida no caso 5
            ViewBag.PaginaAtual = 1; //Aqui informamos a pagina selecionado quando o usuario faz um get a pagina inicial sempre será 1
            ViewBag.QuantPaginas = (GrupoProdutoModel.QuantTotal() / ViewBag.QtdMaximaLinhasPagina);
            ViewBag.QuantPaginas = (GrupoProdutoModel.QuantTotal() % ViewBag.QtdMaximaLinhasPagina) > 0 ? ViewBag.QuantPaginas + 1 : ViewBag.QuantPaginas;
            return View(lista);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public JsonResult GrupoProdutoPagina(int pagina, int tamPag)
        {
            ViewBag.QtdMaximaLinhasPagina = tamPag; //Quando estamos fazendo paginação é necessario informar a quantidade de linhas da table será exibida no caso 5
            var lista = GrupoProdutoModel.RecuperarLista(pagina, tamPag);
            ViewBag.QuantPaginas = (GrupoProdutoModel.QuantTotal() / tamPag);
            ViewBag.QuantPaginas = (GrupoProdutoModel.QuantTotal() % tamPag) > 0 ? ViewBag.QuantPaginas + 1 : ViewBag.QuantPaginas;
            return Json(lista);
        }

        /*Funcionalidade Issue 007*/

    }

}

ControleEstoque/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ControleEstoque.Models;
using Newtonsoft.Json.Linq;

namespace ControleEstoque.Controllers
{
    public class CadastroController : Controller
    {
        #region Usuários

        private const string _senhaPadrao = "1112718822";

        [Authorize]
        public ActionResult Usuario()
        {
            ViewBag.SenhaPadrao = _senhaPadrao;
            return View(UsuarioModel.RecuperarLista());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult RecuperarUsuario(int id)
        {
            return Json(UsuarioModel.findUsuario(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirUsuario(int id)
        {
            return Json(UsuarioModel.deleteUsuario(id));
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult SalvarUsuario(UsuarioModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    if (model.Senha == _senhaPadrao)
                    {
                        model.Senha = "";
                    }

                    var id = model.salvarUsuario();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }

        #endregion

        #region MarcaProduto
        [Authorize]
        public ActionResult MarcaProduto()
        {
            return View();
        }
        #endregion

        #region LocalProduto
        [Authorize]
        public ActionResult LocalProduto()
        {
            return View();
        }
        #endregion

        #region UnidadeMedida
        [Authorize]
        public ActionResult UnidadeMedida()
        {
            return View();
        }
        #endregion

        #region Produto
        [Authorize]
        public ActionResult Produto()
        {
            return View();
        }
        #endregion

        #region Pais
        [Authorize]
        public ActionResult Pais()
        {
            return View();
        }
        #endregion

        #region Ver depois
        [Authorize]
        public ActionResult Estado()
        {
            return View();
        }

        [Authorize]
        public ActionResult Cidade()
        {
            return View();
        }

        [Authorize]
        public ActionResult Fornecedor()
        {
            return View();
        }

        [Authorize]
        public ActionResult PerfilUsuario()
        {
            return View();
        }
        #endregion
    }

}

ControleEstoque/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControleEstoque.Models;
using System.Web.Security;

namespace ControleEstoque.Controllers
{
    public class ContaController : Controller
    {

        [AllowAnonymous] /*Tornando o método Publico*/
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }


            var usuario = UsuarioModel.ValidarUser(login.Usuario, login.Senha);

            if (usuario != null)
            {
                FormsAuthentication.SetAuthCookie(usuario.Nome, login.LembrarMe);/*Criando o Cookie de Autenticação*/

                if (Url.IsLocalUrl(returnUrl)) /*Verificando se a Url está dentro do dominio*/
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home"); /* Se não estiver no dominio redirecionamos para home*/
                }
            }
            else /* Se as crendenciais forem digitadas erradas mostramos uma Mensagem de Erro*/
            {
                ModelState.AddModelError("", "Login Invalido!");
            }
            return View(login);
        }

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

ControleEstoque/Controllers/GraficosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class GraficosController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult PerdaMes()
        {
            return View();
        }
        [Authorize]
        public ActionResult EntradaSaidaMes()
        {
            return View();
        }
    }
}

ControleEstoque/Controllers/OperacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class OperacoesController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult EntradaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult SaidaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult LancPerdaProduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult Inventario()
        {
            return View();
        }
    }
}

ControleEstoque/Controllers/RelatoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class RelatoriosController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult PosicaoEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult Ressuprimento()
        {
            return View();
        }
    }
}

ControleEstoque/Views/Shared/_Cadastro.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@RenderSection("Styles", true) <!--Pega elementos dentro da sction styles nos arquivos que estão importando-->
@RenderBody()

<link href="~/Content/bootstrap-select.css" rel="stylesheet" />
<link href="~/Content/Cadastro/GrupoProduto.css" rel="stylesheet" />

<div id="cadastro">
    <section id="cadastro_cabecalho">
        <h1>@ViewBag.Title</h1>
    </section>
    <section id="cadastro_conteudo">

        <div id="cabecalho_grid" class="row">
            <a id="btn_incluir" class="btn btn-success" role="button"><i class="glyphicon glyphicon-plus"></i> Incluir</a>
            @Html.DropDownList("ddl_tam_pag", (SelectList)ViewBag.ListaTamanhoPag, new { @class = "selectpicker" })
        </div>
        <div class="row">
            <div class="col-md-12">
                <table id="grid_cadastro" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            @RenderSection("TituloGrid", true)
                        </tr>
                    </thead>
                    <tbody>
                        @RenderSection("LinhaGrid", true)
                    </tbody>
                </table>
            </div>
            <!--Paginação-->
            <nav>
                <ul class="pagination">
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    @for (int i = 2; i <= ViewBag.QuantPaginas; i++)
                    {
                        <li class="page-item"><a class="page-link" href="#">@i</a></li>
                    }
                </ul>
            </nav>
        </div>
    </section>
</div>
@Html.Hidden("id_cadastro")
<div id="modal_cadastro" class="form-horizontal" style="display:none" role="dialog">
    <div id="msg_error_aviso" class="text-danger"></div>
    <fieldset>
        @Html.AntiForgeryToken() <!--Gera o token de verificação-->
        @RenderSection("CamposCadastro", true);
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="modal-footer">
                        <a id="btn_sair" class="btn btn-default" role="button" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i>Sair</a>
                        <a id="btn_confirmar" class="btn btn-primary" role="button"><i class="glyphicon glyphicon-ok"></i> Salvar</a>
                    </div>
                    <div id="msg_aviso" class="alert alert-warning">Falta preencher os campos acima!</div>
                    <div id="msg_error" class="alert alert-danger">Ops deu ruim!</div>
                </div>
            </div>
        </div>
    </fieldset>
</div>

@section Scripts{
    @RenderSection("Scripts", true);
    <script src="~/Scripts/Cadastro/CadBase.js"></script>
}

ControleEstoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MySystem", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastro
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Grupos de produtos", "Index", "GrupoProduto")</li>
                                <li>@Html.ActionLink("Marcas de produtos", "MarcaProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Locais de armazenamento", "LocalProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Unidades de medida", "UnidadeMedida", "Cadastro")</li>
                                <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                                <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                                <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                                <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                                <li>@Html.ActionLink("Fornecedores", "Fornecedor", "Cadastro")</li>
                                <li>@Html.ActionLink("Perfis de Usuários", "PerfilUsuario", "Cadastro")</li>
                                <li>@Html.ActionLink("Usuários", "Usuario", "Cadastro")</li>

                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Operações
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Entrada de Produtos", "EntradaEstoque", "Operacoes")</li>
                                <li>@Html.ActionLink("Saída de Produtos", "SaidaEstoque", "Operacoes")</li>
                                <li>@Html.ActionLink("Lançamento de Perdas de Produtos", "LancPerdaProduto", "Operacoes")</li>
                                <li>@Html.ActionLink("Inventário de estoque", "Inventario", "Operacoes")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Relatórios
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Posição do Estoque", "PosicaoEstoque", "Relatorios")</li>
                                <li>@Html.ActionLink("Ressuprimento", "Ressuprimento", "Relatorios")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Gráficos
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Perdas por mês", "PerdaMes", "Graficos")</li>
                                <li>@Html.ActionLink("Entradas vs saídas por mês", "EntradaSaidaMes", "Graficos")</li>
                            </ul>
                        </li>
                    </ul>
                    using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li><a href="#">Olá @User.Identity.Name</a></li>


                            <li><a href="javascript:document.getElementById('logoffForm').submit()">Sair</a></li>

                            
                        </ul>
                        }
                    }
                     else
                         {
                              <ul class="nav navbar-nav navbar-right">
                                  <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                              </ul>

                        }
                    </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>